export const photos = [
  { src: "/wedding_img/wed_img_3.jpg" },
  { src: "/wedding_img/wed_img_4.jpg" },
  { src: "/wedding_img/wed_img_5.jpg" },
  { src: "/wedding_img/wed_img_6.jpg" },
  { src: "/wedding_img/wed_img_7.jpg" },
  { src: "/wedding_img/wed_img_8.jpg" },
  { src: "/wedding_img/wed_img_9.jpg" },
  { src: "/wedding_img/wed_img_10.jpg" },
  { src: "/wedding_img/wed_img_11.jpg" },
  { src: "/wedding_img/wed_img_12.jpg" },
  { src: "/wedding_img/wed_img_13.jpg" },
  { src: "/wedding_img/wed_img_14.jpg" },
  { src: "/wedding_img/wed_img_16.jpg" },
  { src: "/wedding_img/wed_img_18.jpg" },
  { src: "/wedding_img/wed_img_19.jpg" },
  { src: "/wedding_img/wed_img_20.jpg" },
  { src: "/wedding_img/wed_img_21.jpg" },
  { src: "/wedding_img/wed_img_22.jpg" },
  { src: "/wedding_img/wed_img_23.jpg" },
  { src: "/wedding_img/wed_img_24.jpg" },
  { src: "/wedding_img/wed_img_27.jpg" },
  { src: "/wedding_img/wed_img_15.jpg" },
  { src: "/wedding_img/wed_img_1.jpg" },
  { src: "/wedding_img/wed_img_2.jpg" },
  { src: "/wedding_img/wed_img_25.jpg" },
  { src: "/wedding_img/wed_img_26.jpg" },
];
